#!/usr/bin/env sh
base_dir=$(cd $(dirname $0)/..; pwd)
pushd "$base_dir/kubernetes/couchdb"

oc -n openwhisk create secret generic db.auth \
    --from-literal=db_username=whisk_admin \
    --from-literal=db_password=some_passw0rd

oc -n openwhisk create configmap db.config \
    --from-literal=db_protocol=http \
    --from-literal=db_provider=CouchDB \
    --from-literal=db_whisk_activations=test_activations \
    --from-literal=db_whisk_actions=test_whisks \
    --from-literal=db_whisk_auths=test_subjects \
    --from-literal=db_prefix=test_

cat couchdb.yml |
    perl -pe 's|networking.k8s.io/v1|extensions/v1beta1|' |
oc -n openwhisk apply -f -

sleep 5

oc -n openwhisk logs $(oc get pod -l name=couchdb -o name) |
    perl -pe 'if (/successfully setup and configured CouchDB for OpenWhisk/) { print $_; print "COMPLETED.\n"; exit 0; }'

# TODO: persistent volume...
